### PR TITLE
First mapping

### PR DESCRIPTION
**Pull request by LienReyserhove**
This is a first attempt to map the data. Now ok for review. 
A summary of the Darwin Core terms and other remarks below.

### Pre-processing

1. The scientific names were cleaned using the namerparser() function provided by rgbif
2. Generate taxonID's

### Taxon core
Information on classification (`kingdom`, `phylum`, `class`, `order`) was interpreted by myself. Might be doublechecked

- [x] language
- [x] rightsHolder
- [x] datasetID
- [x] datasetName
- [x] taxonID
- [x] scientificName
- [x] kingdom
- [x] phylum
- [x] class
- [x] order
- [x] higherClassification
- [x] taxonRank

### Literature Reference extension

1. A new raw file `reference.xlsx` was generated, with reference information contained in the supplementary information.
2. Reference number infomration in the raw data file was cleaned using the function `colon_to_seq` (thanks to @stijnvanhoey )

- [x] taxonID
- [x] identifier
- [x] bibliographicCitation

### Distribution extension

1. Date and country information was rearranged (from 8 to 2 columns)
2. For `eventDate`: 2016 was taken as the end date (year of the publication)

- [x] taxonID
- [x] locationID
- [x] locality
- [x] countryCode
- [x] occurrenceStatus
- [x] establishmentMeans
- [x] eventDate
- [x] source

### Species Profile extension

- [x] taxonID
- [x] isMarine
- [x] isFreshwater
- [x] isTerrestrial

### Description extension

1. Native range: information was mapped (when possible) to the WGSRPD standard
2. Pathway information: complicated! See also #3 

- [x] taxonID
- [x] description
- [x] type
- [x] source
- [x] language

### CODE REVIEW

**Comment by peterdesmet** [comment]
What is the DOI of the paper and link to the source file? Would include this in the README (for sure) and maybe also in the Rmd. Same for the references file: what is the link on which this file was based?

**Comment by peterdesmet** [comment]
I'm starting my review here, will let you know when it's finished:

1. I would include (and document in the Rmd) the following two mappings:
    - `phylum: Magnoliophyta`: Angiospermae = Magnoliophyta (https://en.wikipedia.org/wiki/Flowering_plant) => is a phylum (https://www.gbif.org/species/49)
    - `class: Actinopterygii`: Osteichthyes includes Actinopterygii and Sarcopterygii (https://en.wikipedia.org/wiki/Osteichthyes) => I think all ours are Actinopterygii which is a class

**Comment by LienReyserhove** [comment]
With respect to [this comment](https://github.com/trias-project/rinse-pathways-checklist/pull/6#issuecomment-394744591):

I agree that we should include the link to the source file in the README, in a similar way as we did this for the other checklist. The doi and link to the supplementary material could also be provided in the metadata, in a similar way as we did this for the alien macroinvertebrates. We could do this for the .Rmd as well, but we should keep the same approach for each checklist.

**Comment by LienReyserhove** [comment]
More concretely, I would approach it like this:

1. README:
- Rationale: link to the original file (here: supplementary word document table 2).
- Workflow: keep approach as it is, i.e. refer to the source file found on GitHub

2. Metadata:
- Refer to the DOI of the paper and if necessary, where to find the original data (in this case supplementary material)
- Describe the whole process in detail in the step description section of the metadata (here: download supplementary material, transform it to an Excel file, perform mapping, etc.)

3. .Rmd

- No specific link to the exact location of the source file in the .Rmd, only to the raw data file in the GitHub repo (i.e. keep the situation as it is)

**Comment by LienReyserhove** [comment]
I also included a suggestion for the README to this PR

**Comment by peterdesmet** [comment]
Better documentation of pathway/vector decision can be tackled after this PR

**Comment by peterdesmet** [comment]
Nice work! Ok to merge

**Pull request merged**
